 
name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make executable (build.sh)
      run: chmod +x ./build.sh
    - name: Build with Maven
      run: ./build.sh
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/*.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true